class FuseZip < Formula
  desc "FUSE file system to create & manipulate ZIP archives"
  homepage "https://bitbucket.org/agalanin/fuse-zip"
  # Return to the non-autogenerated tarballs (on the "Downloads" tab), when
  # possible. 0.7.1 is missing for now, so we use the autogenerated tag tarball.
  url "https://bitbucket.org/agalanin/fuse-zip/get/0.7.1.tar.gz"
  sha256 "771302586ca734bf845effcea999c38f4c2e984e29605912eb3470fbeea0b195"
  license "GPL-3.0-or-later"
  head "https://bitbucket.org/agalanin/fuse-zip", using: :hg

  depends_on "pkg-config" => :build
  depends_on "libzip"

  on_macos do
    disable! date: "2021-04-08", because: "requires closed-source macFUSE"
  end

  on_linux do
    depends_on "libfuse"
  end

  def install
    system "make", "prefix=#{prefix}", "install"
  end

  def caveats
    on_macos do
      <<~EOS
        The reasons for disabling this formula can be found here:
          https://github.com/Homebrew/homebrew-core/pull/64491

        An external tap may provide a replacement formula. See:
          https://docs.brew.sh/Interesting-Taps-and-Forks
      EOS
    end
  end

  test do
    system bin/"fuse-zip", "--help"
  end
end
