class Qcachegrind < Formula
  desc "Visualize data generated by Cachegrind and Calltree"
  homepage "https://kcachegrind.github.io/"
  url "https://download.kde.org/stable/release-service/21.08.3/src/kcachegrind-21.08.3.tar.xz"
  sha256 "22e7991609f363cec8ff7b8631c4700fda391f5d6f9894b29727487d7c0915a1"
  license "GPL-2.0-or-later"

  # We don't match versions like 19.07.80 or 19.07.90 where the patch number
  # is 80+ (beta) or 90+ (RC), as these aren't stable releases.
  livecheck do
    url "https://download.kde.org/stable/release-service/"
    regex(%r{href=.*?v?(\d+\.\d+\.(?:(?![89]\d)\d+)(?:\.\d+)*)/?["' >]}i)
  end

  bottle do
    sha256 cellar: :any,                 arm64_big_sur: "d6ca58ecd551e9b556a6953eb219a6ce81fd06e486f4e8f5ad17bef250dbce62"
    sha256 cellar: :any,                 big_sur:       "ec880283d97700b5182c9ef21c7c97a34a892aa6e1b8c5ae77932d674bf3dae9"
    sha256 cellar: :any,                 catalina:      "009247fc3199c6f97a3e57efd1e13987395f3e9a86fc2bd1897d7ab86bb0984e"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "5f36f38f6ab4d12ad121aacbad6b98565384adf611ce02581a6588c26cae697b"
  end

  depends_on "graphviz"
  depends_on "qt@5"

  on_linux do
    depends_on "gcc"
  end

  fails_with gcc: "5"

  def install
    args = ["-config", "release", "-spec"]
    os = OS.mac? ? "macx" : OS.kernel_name.downcase
    compiler = ENV.compiler.to_s.start_with?("gcc") ? "g++" : ENV.compiler
    arch = Hardware::CPU.intel? ? "" : "-#{Hardware::CPU.arch}"
    args << "#{os}-#{compiler}#{arch}"

    system Formula["qt@5"].opt_bin/"qmake", *args
    system "make"

    if OS.mac?
      prefix.install "qcachegrind/qcachegrind.app"
      bin.install_symlink prefix/"qcachegrind.app/Contents/MacOS/qcachegrind"
    else
      bin.install "qcachegrind/qcachegrind"
    end
  end
end
