class Qcachegrind < Formula
  desc "Visualize data generated by Cachegrind and Calltree"
  homepage "https://kcachegrind.github.io/"
  url "https://download.kde.org/stable/release-service/22.04.1/src/kcachegrind-22.04.1.tar.xz"
  sha256 "5af150fc24f36f67f4c86ccb7a5a85067619685c4639fa905195136e84a7785b"
  license "GPL-2.0-or-later"

  # We don't match versions like 19.07.80 or 19.07.90 where the patch number
  # is 80+ (beta) or 90+ (RC), as these aren't stable releases.
  livecheck do
    url "https://download.kde.org/stable/release-service/"
    regex(%r{href=.*?v?(\d+\.\d+\.(?:(?![89]\d)\d+)(?:\.\d+)*)/?["' >]}i)
  end

  bottle do
    sha256 cellar: :any,                 arm64_monterey: "dbe7ebd8d589056ee9826b3c6767eb0f8303d7e3e0c06575faeaa7d7d85e5886"
    sha256 cellar: :any,                 arm64_big_sur:  "97d9d3637ef0d9e8a76a28461b51b7fd8af7671877fb60bf71b51a5380fdd56f"
    sha256 cellar: :any,                 monterey:       "019a4e58506a0fc15eeaaf98849ac5a1353209db472157e78085f4fe1f4911b3"
    sha256 cellar: :any,                 big_sur:        "3e1228906784a429732322e9c740efa95245a3a815ae417f949ddb6f736ae239"
    sha256 cellar: :any,                 catalina:       "e7a40a481513ea144c934bf80af965b5c34d171999e6500fbf303dffb6664099"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "f3ef0afa388e8456cc349b59e6a437ff6b4d3b4fe96ecde576f3727b52d227bc"
  end

  depends_on "graphviz"
  depends_on "qt@5"

  on_linux do
    depends_on "gcc"
  end

  fails_with gcc: "5"

  def install
    args = ["-config", "release", "-spec"]
    os = OS.mac? ? "macx" : OS.kernel_name.downcase
    compiler = ENV.compiler.to_s.start_with?("gcc") ? "g++" : ENV.compiler
    arch = Hardware::CPU.intel? ? "" : "-#{Hardware::CPU.arch}"
    args << "#{os}-#{compiler}#{arch}"

    system Formula["qt@5"].opt_bin/"qmake", *args
    system "make"

    if OS.mac?
      prefix.install "qcachegrind/qcachegrind.app"
      bin.install_symlink prefix/"qcachegrind.app/Contents/MacOS/qcachegrind"
    else
      bin.install "qcachegrind/qcachegrind"
    end
  end
end
